// Generated by CoffeeScript 1.6.3
var Backlist;

Backlist = {};

Blacklist.lists = {
  'title': ['Facebook Connect Helper'],
  'host': ['foobar.foo']
};

Backlist.methods = [];

Backlist["do"] = function(pageTransformer) {
  var $, backlisted, blacklisted, h, t, title, _i, _j, _len, _len1, _ref, _ref1;
  backlisted = false;
  $ = pageTransformer.$;
  title = $('title').text();
  _ref = Backlist.lists.title;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    t = _ref[_i];
    if (title.indexOf(t) >= 0) {
      backlisted = true;
    }
  }
  _ref1 = Backlist.lists.host;
  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
    h = _ref1[_j];
    if (pageTransformer.host.indexOf(h >= 0)) {
      blacklisted = true;
    }
  }
  return blacklisted;
};

module.exports = Blacklist;
