// Generated by CoffeeScript 1.6.3
var app, express, fs, io, removeScripts, savePage, server;

express = require('express');

fs = require('fs');

app = express();

server = require('http').createServer(app);

io = require('socket.io').listen(server);

server.listen(3000);

app.configure(function() {
  return app.use(express["static"](__dirname + '/public'));
});

io.sockets.on('connection', function(socket) {
  socket.on('ping', function() {
    return socket.emit('ready');
  });
  return socket.on('scrape', function(data) {
    var page;
    data = JSON.parse(data);
    page = data.page;
    page = removeScripts(page);
    return savePage(page);
  });
});

savePage = function(html) {
  var timestamp;
  html = '<!DOCTYPE html><html>' + html + '</html>';
  timestamp = new Date().getTime();
  return fs.writeFile('pages/' + timestamp + '.html', html);
};

removeScripts = function(html) {
  var end, search, start;
  search = true;
  while (search) {
    start = html.indexOf('<script');
    end = html.indexOf('</script>');
    if (start > -1 && end > -1) {
      html = html.substring(0, start) + html.substring(end + 9);
    } else {
      search = false;
    }
  }
  return html;
};
